
title: HighResMIP
description: >- # this means to ignore newlines until "baseurl:"
  Design of a successor to the CMIP6 HighResMIP project to allow a multi-model 
  approach to the systematic investigation of the impact of horizontal 
  resolution in climate models. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  HighResMIP2

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
